name: MongoDB Local
values:
  - key: baseUrl
    value: 'http://localhost:8000/api/mongo'
    enabled: true
    type: default
  - key: cliente_id
    value: ''
    enabled: true
    type: default
  - key: product_id
    value: ''
    enabled: true
    type: default
  - key: order_id
    value: ''
    enabled: true
    type: default
